### ISSUE TITLE
Genii badgerdb store

### ISSUE THREAD

**Issue by gedw99** [daptin/daptin#101]
This project is really impressive.

I would like to add a dialogue system in order allow users to leverage the content for real time communication use cases.

But I am finding the dB to be way to slow for this and so I wanted to suggest adding a pure golang sql dB. 
It’s challenged genji and based on badgerdb. I use it on a number of production projects and it’s much faster than the current drives . Benchmarks generally are in the region of 10 to hundred times faster and use less resources.

https://github.com/genjidb/genji

Because it uses badgerdb which has a subscribe command it’s going to work faster with the views functionality and graphQL.

Let me know what you think and I can help if your up for it

- Are you running a release or master: 

Master
- Issue is about a fresh instance (no data in db) or restart:

Fresh

**Comment by gedw99** [comment]
Genji also has streaming backups btw. It’s part of badgerdb. Really useful with HA aspects.

It’s also has encryption at rest with rotating keys. Very enterprise stuff

**Comment by artpar** [comment]
Hey @gedw99 

Genji looks great embedded database (reliable alternative to sqlite backend) and might be a good fit for features with daptin is providing . 

But I am not planning any major feature additions in V1. So if V2 was ever to happen, this should probably make its way to the roadmap.

Regards
