### ISSUE TITLE
Unable to create user or log in via dashboard

### ISSUE THREAD

**Issue by bobbygryzynger** [daptin/daptin#106]
- Are you running a release or master: master
- Issue is about a fresh instance (no data in db) or restart: fresh

### Steps to reproduce
1. Clone https://github.com/daptin/dashboard-classic to `daptin-dashboard`
2. cd `daptin-dashboard` and run `npm install && npm run build`
3. cd `..`
1. Clone https://github.com/daptin/daptin to `daptin`
2. cd `daptin` and run `go build`
5. Run `DAPTIN_DASHBOARD=../daptin-dashboard/dist ./daptin`
6. Go to `http://localhost:6336/auth/signup` and enter form values:

![Screen Shot 2021-03-26 at 12 16 43 AM](https://user-images.githubusercontent.com/6345927/112576422-a23fd500-8dc8-11eb-88dd-56eba35c4a78.png)

Here the request will fail with a `400` error: 
```
[GIN] 2021/03/26 - 00:20:02 | 400 |    4.528326ms |             ::1 | POST     "/action/user_account/signup"
```
The request payload has: 
```json
"attributes": {
    "name": "user",
    "email": "someone@example.com",
    "password": "123",
    "passwordConfirm": "123"
}
```

But the response says that the password is invalid:
```json
[{"ResponseType":"client.notify","Attributes":{"message":"http error (400) min and 0 more errors, invalid value for password","title":"failed","type":"error"}}]
```

I am able to create a new user successfully via a `curl` command, but when trying to log in as the user via the dashboard I get a similar `400` error.

**Comment by artpar** [comment]
Hi

There is a minimum length of 8 characters requirement for password field.


Here is the sign up action defined for reference:
https://github.com/daptin/daptin/blob/59e4224d490fc1e0ac6a54267a4b5e09d5a2fcf3/server/resource/columns.go#L1081

**Comment by bobbygryzynger** [comment]
@artpar that works, thanks for pointing it out in the source.

**Comment by artpar** [comment]
You can add a new action with a change in those constraints and use that for login instead.
