### ISSUE TITLE
Web dashboard fails to open in v0.9.5

### ISSUE THREAD

**Issue by vanruesc** [daptin/daptin#110]
Hi,

the dashboard seems to be broken in v0.9.5. I'm only getting a blank page when I open http://localhost:6336. Daptin logs the following warning:

```sh
time="2021-04-05T17:20:34+02:00" level=info msg="Listening at: [:6336]"
[GIN] 2021/04/05 - 17:20:39 | 200 |            0s |       127.0.0.1 | GET      "/"
[GIN] 2021/04/05 - 17:20:40 | 404 |            0s |       127.0.0.1 | GET      "/favicon.ico"
[GIN] 2021/04/05 - 17:20:43 | 200 |            0s |       127.0.0.1 | GET      "/"
time="2021-04-05T17:21:37+02:00" level=warning msg="Failed to open index.html: open daptinweb\\dist\\spa\\index.html: The system cannot find the path specified."
[GIN] 2021/04/05 - 17:21:37 | 500 |            0s |       127.0.0.1 | GET      "/login"
```

Full log: [daptin-0.9.5.log](https://github.com/daptin/daptin/files/6260435/daptin-0.9.5.log)

- I'm running a release version (daptin-windows-4.0-amd64.exe, [v0.9.5](https://github.com/daptin/daptin/releases/tag/v0.9.5))
- Issue is about a fresh instance (no data in db)
- The dashboard works fine in v0.9.4

Thanks for making and maintaining Daptin 👍

**Comment by artpar** [comment]
Let me figure out what went wrong here. The build logs on github actions seems fine and osx binary seems fine.

**Comment by artpar** [comment]
It's embarrassing that I still don't know why the windows build from github ci isn't embedding dashboard. 

WIP

**Comment by vanruesc** [comment]
No problem, those cross-platform issues can be a real pain to track down.

Are you able to reproduce the issue on your end?

**Comment by artpar** [comment]
Locally it does work. I can probably make a new release and upload the artifacts manually. I am using xgo to generate all the cross platform binaries(the ones that are attached to release). go-rice is being used to embed the static dashboard assets.  

I hope to solve this over the weekend. Should be something trivial.

**Comment by vanruesc** [comment]
I tried out v0.9.6 and can confirm the dashboard works again. Thanks for the quick patch 👍
