### ISSUE TITLE
096version with mysql "panic: interface conversion: interface {} is []uint8, not int64"

### ISSUE THREAD

**Issue by Vladimirang** [daptin/daptin#116]
Please check [open issues](https://github.com/daptin/daptin/issues) before creating a new one to avoid  duplicates.

- Are you running a release or master: release 0.96
- Issue is about a fresh instance (no data in db) or restart: restart

when I run with sqlite, no problem.
When I run with MySQL, the problem as follow:

INFO[0000] We have 0 data exchange updates
INFO[0000] Failed to query config table: <nil>
INFO[0000] No config value set for [langauge.default]: sql: no rows in result set
INFO[0000] We have 0 state machine descriptions
INFO[0000] We have 2 existing streams
INFO[0000] Process stream [table]
INFO[0000] Stream [table] already present in db, updating db values
INFO[0000] Limiting max connections per IP: 100
INFO[0000] Limiting request per second by IP/URL: 100 RPS
INFO[0000] Process stream [transformed_user]
INFO[0000] Stream [transformed_user] already present in db, updating db values
DEBU[0000] making servers
INFO[0000] Starting: 127.0.0.1:2525
INFO[0000] Listening on TCP 127.0.0.1:2525
DEBU[0000] [127.0.0.1:2525] Waiting for a new client. Next Client ID: 1
INFO[0000] main log configured to stderr
INFO[0000] Started mail server
INFO[0000] Token id for store [localstore] is empty
panic: interface conversion: interface {} is []uint8, not int64

goroutine 1 [running]:
github.com/daptin/daptin/server/resource.(*DbResource).GetObjectPermissionByReferenceId(0xc000d5bb80, 0x496afef, 0xb, 0xc000e29170, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /source/server/resource/dbmethods.go:197 +0xb3f
github.com/daptin/daptin/server/resource.(*DbResource).GetAllCloudStores(0xc000d5bb80, 0xc0013d0c90, 0x496afef, 0xb, 0xc0009f6248, 0x0)
        /source/server/resource/dbfunctions_get.go:193 +0x37c
github.com/daptin/daptin/server.CreateSubSites(0xc000d8b700, 0x7aa0388, 0xc000dd0270, 0xc0013d0c90, 0xc000ad6b40, 0xc0012ba700, 0x5, 0x0, 0x0, 0xc0013d0c90)
        /source/server/subsite.go:119 +0x20d
github.com/daptin/daptin/server.Main(0x7a08940, 0xc000c6aa78, 0x7aa0388, 0xc000dd0270, 0x4954387, 0x9, 0xc000e61d40, 0x0, 0xc000dc0800, 0xc000dc07c0, ...)
        /source/server/server.go:419 +0x1dc5
main.main()
        /source/main.go:229 +0xdb7

**Comment by artpar** [comment]
This should be fixed. Tested on my local.
