### ISSUE TITLE
Upload data using csv file format

### ISSUE THREAD

**Issue by Bera** [daptin/daptin#12]
Would be great and useful to upload CSV files as well.

Congrats on this amazing project. I want help and contribute to it.

**Comment by artpar** [comment]
This is available now. Next to the XLS upload on dashboard. 

https://docs.dapt.in/#upload-from-dashboard

**Comment by artpar** [comment]
@Bera I would love more people building and using this. All the help is really appreciated. It would be great if you try it out.

**Comment by Bera** [comment]
@artpar Amazing Job! Thank you! I Will test and learning more about all functionalities and I hope will be able to contributo soon as possible.
