### ISSUE TITLE
Potential security vulnerability

### ISSUE THREAD

**Issue by ranjit-git** [daptin/daptin#120]
Hi, @artpar @parasnarang  @jdrich 

Few Security vulnerability in daptin has been submitted through huntr .
Plz validate them 
https://huntr.dev/bounties/1-other-daptin/daptin/
https://huntr.dev/bounties/2-other-daptin/daptin/
Report is only visible to repo maintainer and reporter .

**Comment by artpar** [comment]
Hi @ranjit-git 

This is a issue in the frontend and not in the server, so have moved the issues to the dashboard repo

https://github.com/daptin/dadadash/issues/2 (in luckysheet grid library)

https://github.com/daptin/dadadash/issues/3 (xss via base-name)

**Comment by ranjit-git** [comment]
it seems already github issue created. Sorry for inconvenience 
@artpar 
can you plz update the report status by going  there so that they can gives bounty to reporter?
https://huntr.dev/bounties/1-other-daptin/daptin/
https://huntr.dev/bounties/2-other-daptin/daptin/
