### ISSUE TITLE
Docs for smtp/imap server

### ISSUE THREAD

**Issue by bil-ash** [daptin/daptin#130]
Please check [open issues](https://github.com/daptin/daptin/issues) before creating a new one to avoid  duplicates.

- Are you running a release or master: latest release
- Issue is about a fresh instance (no data in db) or restart: fresh instance

There are no docs for smtp server at https://daptin.github.io/daptin/features/enable-smtp-imap/ . Please add some.

https://github.com/daptin/daptin/issues/78 suggests that daptin allows dkim. How to get the txt records to be set in the dns server?

Is there any section in the web dashboard for managing smtp server/creating email address?

**Comment by bil-ash** [comment]
Any update on this issue?

**Comment by artpar** [comment]
Hi @bil-ash pushed the documentation to enable smtp/imap and how to configure it

https://daptin.github.io/daptin/features/enable-smtp-imap/

let me know if that helped or needs some changes

**Comment by artpar** [comment]
The classic dashboard has a way to create these mail servers/accounts from the web interface and restart. 

```docker run -p 8080:8080 daptin/dashboard-classic```

**Comment by bil-ash** [comment]
A few queries-
1) `curl 'http://localhost:8080/api/mail_server' -X POST \
  -H 'Content-Type: application/vnd.api+json' \
  -H 'Authorization: Bearer <TOKEN>' \
  --data-raw '{"data":{"type":"mail_server","attributes":{"always_on_tls":true,"authentication_required":true,"hostname":"mail.example.com","is_enabled":true,"listen_interface":"0.0.0.0:465","max_clients":"20","max_size":"10000","permission":0,"xclient_on":false}},"meta":{}}'
`
In creating a mail server,what do the max_size, permission and xclient_on attributes stand for? I understood the other attributes.

2) `curl 'http://localhost:8080/api/mail_account' -X POST \
  -H 'Content-Type: application/vnd.api+json' \
  -H 'Authorization: Bearer <TOKEN>' \
  --data-raw '{"data":{"type":"mail_account","attributes":{"password":"password","password_md5":"password","permission":0,"username":"email-address"},"relationships":{"mail_server_id":{"data":{"id":"e494c2d1-ff68-4ed5-bf9c-b4804aeec0fb","type":"mail_server"}}}},"meta":{}}'
`
In creating an e-mail account, do we have to provide both password and password_md5 attribute? From where can we get the id sub-attribute of the data attribute? 

3) The current version of daptin uses dadadash by default. From the docs at https://daptin.github.io/daptin/setting-up/installation/ and https://github.com/daptin/dashboard-classic , it seems that for using the classic dashboard (in VPS,not docker) I would have to build the classic dashboard using npm and the start daptin using `./daptin -dashboard classic/built` (assuming the classic dashboard gets built into the classic/built directory  and sqlite is used) . Am I correct?

**Comment by artpar** [comment]
Hi

1. MaxClients and MaxSize described here

        
    // Hostname will be used in the server's reply to HELO/EHLO. If TLS enabled
	// make sure that the Hostname matches the cert. Defaults to os.Hostname()
	// Hostname will also be used to fill the 'Host' property when the "RCPT TO" address is
	// addressed to just <postmaster>
	Hostname string `json:"host_name"`
	// Listen interface specified in <ip>:<port> - defaults to 127.0.0.1:2525
	ListenInterface string `json:"listen_interface"`
	**// MaxSize is the maximum size of an email that will be accepted for delivery.
	// Defaults to 10 Mebibytes
	MaxSize int64 `json:"max_size"`**
	// Timeout specifies the connection timeout in seconds. Defaults to 30
	Timeout int `json:"timeout"`
	**// MaxClients controls how many maximum clients we can handle at once.
	// Defaults to defaultMaxClients
	MaxClients int `json:"max_clients"`**
	// IsEnabled set to true to start the server, false will ignore it
	IsEnabled bool `json:"is_enabled"`
	// XClientOn when using a proxy such as Nginx, XCLIENT command is used to pass the
	// original client's IP address & client's HELO


2. You have to give your plain text password in the request, same for both password and password_md5. The server will convert it to the transformed values before saving.

3. Yes that would be the way to go about it. Although it shouldn't be too hard to setup a quick ci/cd job to push docker image with classic dashboard as well.

**Comment by bil-ash** [comment]
Thanks, closing this issue for now, will re-open later if necessary
