### ISSUE TITLE
Old latest image tag on docker hub

### ISSUE THREAD

**Issue by 0x111** [daptin/daptin#134]
Hello @artpar 

I noticed while using the docker version, that on the docker hub the `latest` tag points to a 2 year old version and not the v0.9.9 which would make sense I believe.

https://hub.docker.com/r/daptin/daptin/tags

Could I kindly ask you to set the latest version to the latest new version?
Thank you!

- Are you running a release or master: not relevant
- Issue is about a fresh instance (no data in db) or restart: not relevant

**Comment by artpar** [comment]
Hi @0x111 

Have updated the latest tag. Be sure to check out the admin page when you use [dadadash](https://github.com/daptin/dadadash). 

/#/admin
