### ISSUE TITLE
Native binary for the latest release (0.9.9)

### ISSUE THREAD

**Issue by vinifrancosilva** [daptin/daptin#136]
Hello guys!

I´m new to Go lang and I´m trying to deploy daptin in an intranet isolated debian server. 

It has no internet connection and the native binary deploy would be perfect for my use case but in the last release there was not binaries, only source code.

How can I solve this problem?

Thank you very much!

**Comment by artpar** [comment]
Hey @vinifrancosilva I can upload binary for you. Let me know the arch/os, and if you want to the build embedded with the default dashboard or just the server ?

**Comment by vinifrancosilva** [comment]
> Hey @vinifrancosilva I can upload binary for you. Let me know the arch/os, and if you want to the build embedded with the default dashboard or just the server ?

Thank you very much! 

My setup is debian 11 linux/amd64
Please, with the default dashboard.

I'm still learning how to use it... I want to expose some existing tables for read only they API... Any tips?

Thank you very much for this.

**Comment by artpar** [comment]
Hey @vinifrancosilva 

I ended up building it for all platforms, you can find the binaries here

https://github.com/daptin/daptin/releases/tag/v0.9.9

For creating the table and exposing it as read only, you can create a table, add data to it, and give read/peek permission to guest on both the table/rows. Adding links to relevant docs:

https://daptin.github.io/docs/setting-up/data_modeling/
https://daptin.github.io/docs/setting-up/access/#permission-model

When you signup/login for the first time using the dashboard, it will automatically invoke the API to make your user as the administrator. Do open an issue if you are facing trouble using it.

**Comment by vinifrancosilva** [comment]
Thank you very much! 

I´m going to try here, but I want to expose an existing table from a system at production right now. I gonna setup a test env and try to make it work. If I can´t do it by my own, I will catch with you at discord to not open another issue here.

Thank you for your help.

**Comment by artpar** [comment]
Hey @vinifrancosilva you wont be able to expose an existing table as it is. 

Daptin needs to maintain the table structure, specifically for authn/authz but also for relations. There are certain columns which daptin expects in the table (like permissions and user_id) for that.

**Comment by vinifrancosilva** [comment]
Got it! 

I´ll have to write the api myself then.

Thank you for your time!

**Comment by artpar** [comment]
If you are using postgres, you can checkout something like https://postgrest.org/en/stable/

**Comment by vinifrancosilva** [comment]
Hey @artpar, this is great!

Unfortunately I´m on MS Sql Server. Gonna look for something similar.

Thank you very much for sharing

**Comment by vinifrancosilva** [comment]
Hi @artpar, me again! lol

I tried to deploy it in our serve here and the DadaDash do not load... it renders a white/blank page

The console has 3 errors:

![image](https://user-images.githubusercontent.com/63023796/210562742-81919bfc-6b0d-43ae-a9e4-00ff58cb2bc3.png)

**Comment by artpar** [comment]
Hi @vinifrancosilva 

I think I missed something in the build step and so the binaries did not actually have the dashboard resource files embedded. I have deleted those binaries and rebuild and reuploaded. Have verified the build this time so this one should be good.

https://github.com/daptin/daptin/releases/tag/v0.9.9

**Comment by vinifrancosilva** [comment]
Hi @artpar !

Thank you very much!
