### ISSUE TITLE
Signup on MAC local build fail with 403 error. 

### ISSUE THREAD

**Issue by hrqiang** [daptin/daptin#24]
build on MAC with latest code and still cannot signup. Please help. Thanks.

**Comment by artpar** [comment]
Hi,

Can you remove the database and start from scratch ? I suspect that when you ran it earlier from the bad commit, the database it created is still there.

If you were using MySQL or PostgreSQL, you can just drop the schema you were using. 
If you were using sqlite, then delete the sqlite db file.
