### ISSUE TITLE
Add a public chat option for eaier support and community building

### ISSUE THREAD

**Issue by rishavs** [daptin/daptin#34]
Please look at the option of using Gitter/Slack/Dicourse etc to host a public chatroom where the community can ask questions and support each other. Currently, there is nowhere one can go for help (other than the Github issues)

**Comment by artpar** [comment]
I know you already joined slack, adding link here for others.

Join on slack using this:

https://join.slack.com/t/daptin/shared_invite/enQtMzM1NTM1NTkyMDgzLTVlYzBlMmM4YjMyOTk0MDc5MWJmMzFlMTliNzQwYjcxMzc5Mjk0YzEyZDIwYTljZmE5NDU3Yjk3YzQ3MzhkMzI

**Comment by rishavs** [comment]
@artpar i think it will be great if we can have a prominent link on the webpage and a slack button on github. I was lucky in finding the chatroom as I know a lot of go frameworks use gophers.slack but many people wouldn't know that.

**Comment by artpar** [comment]
Really its the first button right under the logo on readme, I was hoping its really noticeable but I think you missed it :) Let me know where were you searching for it, I'll add it there as well.

**Comment by rishavs** [comment]
my bad. I cant believe, I missed it. I think the main hosted site doesnt have the link yet so I suppose we can add it there

**Comment by artpar** [comment]
Sure will add it there as well. Thanks
