### ISSUE TITLE
Relations dissapear

### ISSUE THREAD

**Issue by JLKM** [daptin/daptin#40]
I'm having trouble adding new relations to my article table/form. Relations go to two new tables (Person and Category), which were created incl. three records each - before creating the article table.

On one hand the relations seem to be present. Still they don't show up on the form. The difference should be visible on the two attached screenshots.

![daptinarticleformwithoutpersoncategoryrelations](https://user-images.githubusercontent.com/18215374/47255199-6b359e80-d46d-11e8-9766-f6b2a0955d31.PNG)

![daptinarticleformwithpersoncategoryrelations](https://user-images.githubusercontent.com/18215374/47255200-6ec92580-d46d-11e8-8b79-7f8c7bc9f6de.PNG)

I realize, that the dissapearance probably has to do with the edge-tables, that you set up between the nodes, you want to connect. But exactly how do you do that?

##### Relations-test on main form with four types of relations. Revealed pattern so far:

| Relation | Visible on main form | Auto-created M2M-table | Auto created M2M-table on dashboard | 
| -------- | -------- | -------- | -------- |
| `Belongs to` | Yes | No  | No |
| `Has one` | Yes | No | No |
| `Has many` | No | Yes | No |
| `Has many and belongs to many` | No | Yes | Yes |

How to proceed from here?

My Daptin is running in Windows 10 with Sqlite as backend.

**Comment by artpar** [comment]
Hi @JLKM 

That is correct. The relations will not come up on the entity instance editor form. That is just a UI choice I made for the embedded dashboard (i am not good in ui/ux).

You will be able to view/edit relations in the "detail view" of the instance.

To walk you thru a bit, check out the following images from one of my sites. I have a "merchant" entity which "has many" Integration (another entity)

This page is the list of "Merchant" entity, showing all the instances of merchants (the card view)
<img width="1440" alt="screen shot 2018-10-22 at 10 53 22 am" src="https://user-images.githubusercontent.com/1142886/47278730-d788dd00-d5e8-11e8-85cc-29c147595791.png">

This is the creation form of the merchant, which does not show related entities
<img width="1445" alt="screen shot 2018-10-22 at 10 53 29 am" src="https://user-images.githubusercontent.com/1142886/47278731-d8ba0a00-d5e8-11e8-9eec-570a05f9ba4c.png">


Note the "expand" arrow in the card view in first image, clicking that for one merchant gives me the detailed view of that merchant, which now includes a tab for related entities
<img width="1398" alt="screen shot 2018-10-22 at 10 56 03 am" src="https://user-images.githubusercontent.com/1142886/47278782-3a7a7400-d5e9-11e8-9caf-16b9df1501aa.png">


<img width="1415" alt="screen shot 2018-10-22 at 10 57 01 am" src="https://user-images.githubusercontent.com/1142886/47278785-3e0dfb00-d5e9-11e8-8010-a6f96eec85d0.png">

Adding/Removing related entities can be done from the above part.

Again, I want to reiterate that this web dashboard is just to get started quick and I am really bad in ui/ux decisions so please excuse the ui choices :) .
