### ISSUE TITLE
Documentation on how to extend/override functionality 

### ISSUE THREAD

**Issue by rrjanbiah** [daptin/daptin#44]
Project features set looks extremely nice. Looks like this is what we were waiting for (?) https://github.com/RestyaPlatform/board/issues/1250

Is there any documentation or sample projects on how to extend or override any endpoints? Looks like there's some option for middleware. But, is there any rough documentation or sample snippet for the same? TIA

**Comment by artpar** [comment]
Thanks for this. Slightly longer answer, let me write some overview around it and add here itself for the moment.

**Comment by artpar** [comment]
There are multiple points of extension, apologies for lack of documentation. Let me write a brief overview:


## Middlewares in the CRUD API

For frequently used operations in CRUD APIs, middlewares easy to use extension points. For advanced extensions checkout Actions.

Middlewares can be hooked AFTER or BEFORE a CRUD API is invoked, so you can perform extra actions before or after some data changes in the system.
Middleware implementations are written in gocode of the system and currently the following four middlewares are available:

- Data validation
  Data validation middleware is always invoked but does nothing by default. Validations are used to reject a request if certain field of the request is not according to required format. 
  List of available validator options can be found here: https://godoc.org/gopkg.in/go-playground/validator.v9
  Validations are declared in the table schema, usage example:

```
  				ColumnName: "password",
				Tags:       "required,eqfield=InnerStructField[passwordConfirm],min=8",
```
  
- Conformations 
  Conformations is also part of this middleware and can be used to execute basic cleaning of user input before storing data. 
  List of available conformations: https://github.com/leebenson/conform

```
  				ColumnName: "email",
				Tags:       "email,trim",
```



- Exchange middleware
  This can be used to call an external endpoint on a CRUD API invocation. As an example, the following schema defines sync'ing of the todo list items to a google-spreasheet:
  https://github.com/daptin/market/blob/master/todolist/schema_todolist_daptin.yaml#L180

- Authorizations
Row and Table level authorizations is also implemented as middlewares.


## Actions

Actions give you complete control of the flow for your new API. 
Various APIs in daptin are already implemented as actions, like Signup/SignIn. You can use Javascript inside actions. 

Checkout documentation here to create a new action:
https://daptin.github.io/docs/actions/actions/ 

Here is a list of existing actions:
https://daptin.github.io/docs/actions/default_actions/

**Comment by rrjanbiah** [comment]
@artpar Thank you so much! Will try and let you know. Thanks again!
