### ISSUE TITLE
More properties on join table 

### ISSUE THREAD

**Issue by JLKM** [daptin/daptin#45]
The relations in Daptin - like `has many`, `belongs to` etc. - are concepts from graph database systems, where they describe the edges (the relation entities connecting the nodes).

The `has many`-relation in Daptin auto-creates a join-table (a kind of edge), and this behavior makes Daptin even more "graphy".

In graph databases, though, edges have more properties - like: personA `like`/`dislike`/`has visited`/`is married to` etc. personB. Is this possible with Daptin, or have I missed something here?

**Comment by JLKM** [comment]
Very interesting feedback, indeed. Especially the part with multiple relationships between two entities.

But isn't it so, that each relationship (is_married_to, likes, is_sibling_to etc.) produces its own join table, where a true graph db setup would combine those relationships between two nodes in one single edge-table (for ultra high serach-speed)?

**Comment by artpar** [comment]
Join table is created only for a many-to-many relation (has many), belongs_to and has_one adds a column to the corresponding table. So for example each object belongs to a user and can belong to multiple usergroups, so each table has a ```user_account_id``` column and each table has a join table for maintaining the usergroups which it belongs to.

As for the speed of search/join, when storing data in a relational database, it would most certainly be dependent on the following factors:

- Organization of data (normalization)
- Query itself
- Indexes
- Key constraints

The db created by daptin behind the scene is in BCNF. Queries made to the database mostly rely on joins and foreign keys when fetching related data. This gives me certain surety of high throughput. 

You can verify this by logging into the DB itself (mysql-cli for example) and do a ```show create table <tableName>```, which will give something as following (an example)


```
CREATE TABLE `person` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `version` int(11) NOT NULL DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL,
  `reference_id` varchar(40) NOT NULL,
  `permission` int(11) NOT NULL,
  `person_name` varchar(500) NOT NULL,
  `age` int(11) NOT NULL,
  `spouse` int(11) DEFAULT NULL,
  `place_id` int(11) DEFAULT NULL,
  `user_account_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `74aae991424c75393f1630176394f3f6` (`reference_id`),
  UNIQUE KEY `u3d15ac6e28afa02eb4033816a0f2a4ef` (`reference_id`),
  KEY `fk34b4ab84b97fd92a962e8799584d8aaf` (`spouse`),
  KEY `fk45f1cc29e41527df8f313386a694df83` (`place_id`),
  KEY `fk80bad20c5ae9e5c6ddf73bd4ece99ac0` (`user_account_id`),
  KEY `i6f34dc6944938770b9e13356c2f98913` (`created_at`),
  KEY `i689518ffa111bf9a2cc231e232e0cfba` (`updated_at`),
  CONSTRAINT `fk34b4ab84b97fd92a962e8799584d8aaf` FOREIGN KEY (`spouse`) REFERENCES `person` (`id`),
  CONSTRAINT `fk45f1cc29e41527df8f313386a694df83` FOREIGN KEY (`place_id`) REFERENCES `place` (`id`),
  CONSTRAINT `fk80bad20c5ae9e5c6ddf73bd4ece99ac0` FOREIGN KEY (`user_account_id`) REFERENCES `user_account` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci```

But if you still come across a scenario where daptin is the bottleneck in your application, I would love to go into detail and identify areas where that can be improved.

**Comment by JLKM** [comment]
Perhaps you lost me here. But what I'm looking for, is a "Fat Edge" within the Daptin system. By this I mean both a one-to-one and a one-to-many relation, where the relation carries extra information - f.ex. inactive/active, starttime, endtime. Please take a look at the illustration attached.

**Comment by JLKM** [comment]
Very much appreciate your enthisiasm and speed. And I know that much, that data are going to be sparse (there will be blanks). But unfortunately I'm not able to give you much feedback on API design...

My hope is, though, that Daptin might become the GUI/webadmin of choice for people, who want to build up a graph database system without worrying too much about APIs and JSON-structures.

To my knowledge this goal does not in any way conflict with using Sqlite as backend, like Daptin does. Graph databases, at least in my view, is a way of structuring (relational) data. The main difference being the focus on supporting those "fat edges", which contain al relations between entities. Example:

| Id | PersonKey | PlaceKey | Status | StartTime | EndTime | Relation |
| -------- | -------- | -------- | -------- | -------- | -------- | -------- |
| 00000001 | PeterTownsendKey | IBMkey | Inactive | 01-01-1988 | 01-09-2008 | Employee |
| 00000002 | CliveBarkleyKey | IBMkey | Active | - | - | Shareholder |
| 00000003 | EstherBeanKey | DeutscheBankKey | Active | - | - | Customer |

This is, technically, a pretty ordinary joinTable. But, content-wise, it's a graph - due to the collection of all types om relations between two entities in the same (edge)-table.

Daptin allready offers the lookup from - say person to place - in one screen, if it's a one-to-one relation. But it might be possible to extend this one-screen approach into a one-to-many relation and with more fields attached to it (the "fat edge").

Some would perhaps call this "saving triples" or a RFD-approach. Nevertheless, it's something along those lines, that I need. A headless graph CMS, but with a userfriendly webinterface!

Having this in place, only the frontend needs to be taken care of. Fortunately we've got Vue for that. Yes, I'm also a very big fan of this independent library, which soon will surpass Botstrap and become the most starred frontend library on GitHub ever.

**Comment by artpar** [comment]
This is available now.
