### ISSUE TITLE
Easy way to get markdown content rendered

### ISSUE THREAD

**Issue by JLKM** [daptin/daptin#46]
Having markdown syntax rendered in Daptin seems to be possible according to [this doc](https://github.com/daptin/daptin/blob/efefcce28948af3f2a542fc9293d921059c2bcb7/docs_markdown/cinder/docs/specimen.md).

Is there an easy way?

How about developing this as a built in feature in connection with the `content`-field type?

**Comment by JLKM** [comment]
My suggestion is only targeted at enhancing the admin interface. F.ex. here:

http://localhost:6336/in/item/tablename where html fields are rendered nicely

and perhaps here:

http://localhost:6336/in/item/tablename/unid where html fields don't seem to get rendered either at the moment

**Comment by artpar** [comment]
Pushed in master.
