### ISSUE TITLE
Remove columns in Online entity designer

### ISSUE THREAD

**Issue by JLKM** [daptin/daptin#47]
Adding columns in Online entity designer works like a charm. But how about removing columns. This doesn't seem to be possible at present. At least not here, where only plusses (not minusses) are available:

http://localhost:6336/in/meta/new?table=tablename

**Comment by artpar** [comment]
Hi @JLKM,

Yes that's correct, there is no option of removing columns at the moment. Will be present in the next major release (expect a month).

**Comment by artpar** [comment]
Started writing the action implementation for deleting a column here:

https://github.com/daptin/daptin/blob/action_delete_column/server/resource/action_delete_column.go#L28

Using `columnName` and `tableName` build a sql query to alter table and drop column.

The sql query need to be specific to the currently selected db driver: `mysql`, `postgres` or `sqlite` (if there are any differences)

The schema for the table need to be updated in the `world` table. Here is one example of schema being updated using the code:

https://github.com/daptin/daptin/blob/action_delete_column/server/resource/dbfunctions_update.go#L988

Schema is just JSON representation of [TableInfo](https://godoc.org/github.com/daptin/daptin/server/resource#TableInfo). Fetching existing from db, unmarshal to structure, delete column, marshall to json and update to db.

**Comment by artpar** [comment]
Merged in daptin@66c9df7c87b7f66af536b72eadc9195e900aa014
Will be available in next release.
