### ISSUE TITLE
User sign up issue from a website

### ISSUE THREAD

**Issue by phanikumar252** [daptin/daptin#48]
hi, i have been tryng to creat a new account from my website using backend as daptin but everytime i am getting 403 forbidden error .Please help to resolve this issue thank you.

url: http://localhost:6336/action/user/signup,
my post params are :
{
"attributes": {
"first_name": "kumar",
"last_name": "charan",
"email": "test@example.com",
"password": "xxxxxx"
}
}
![screenshot at 2019-02-15 12 33 14](https://user-images.githubusercontent.com/47655676/52850208-f0d60c00-3138-11e9-84d2-10cfeb6fe51c.png)

**Comment by artpar** [comment]
Hi @phanikumar252 

Please try this CURL requst

```curl 'http://localhost:9898/action/user_account/signup'  --data '{"attributes":{"name":"name","email":"email@test.com","password":"password","passwordConfirm":"password"}}'```


Do note that the "user" entity was recently changed to user_account since mysql introduced a new "user" keyword in MySQL 8

**Comment by phanikumar252** [comment]
ok thak you for your suggesation  @artpar ,

i will change my request as you said.

**Comment by phanikumar252** [comment]
hi @artpar,

when i am trying above scenario, i am getting this error

<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /api/v1</pre>
</body>
</html>

**Comment by artpar** [comment]
Can you attach a complete screenshot with the network tab logs of the browser ?

You should be calling `/action/user_account/signup` and not `/api/v1`

**Comment by phanikumar252** [comment]
sorry for that , please check these screenshots @artpar 
![screenshot at 2019-02-15 14 20 46](https://user-images.githubusercontent.com/47655676/52845364-ef9ee200-312c-11e9-920c-df82c1cd2b8f.png)
![screenshot at 2019-02-15 14 20 54](https://user-images.githubusercontent.com/47655676/52845371-f4639600-312c-11e9-93b1-879eac056734.png)

**Comment by artpar** [comment]
Yes,`name` field is missing in the request you are sending and it is a required field (you can change this later or use some dummy name). Use this:

```json
{
    "attributes": {
        "name":"name",
        "email":"email@test.com",
        "password":"password",
        "passwordConfirm":"password"
    }
}
```

**Comment by phanikumar252** [comment]
ok, thank you seems it will definately help to me @artpar

**Comment by phanikumar252** [comment]
hi @artpar ,

Its working now and i have a small doubt how i can add new fields in signup in daptin, 

for example i need to post data like this

{"attributes":{
        "first_name": firstName,
        "last_name": lastName,
        "email":email,
        "password":password,
      }}

**Comment by phanikumar252** [comment]
hi @artpar ,

Now i became admin for the site but new user cannot able to signup and i checked this link https://docs.dapt.in/#become-admin but when clicked on this 'Enable sign up for guests' it is redirecting to signin process. So please help in giving permission for signing up new user.

I have enabled permissions like this for guests
![screenshot at 2019-02-15 17 54 47](https://user-images.githubusercontent.com/47655676/52856983-d2c5d700-314b-11e9-8314-638783e8734d.png)

**Comment by phanikumar252** [comment]
hi @artpar ,

I have enabled all permissions in sign up table for the guests now it is working for me. 

Is this correct way to do this?
![screenshot at 2019-02-15 18 41 07](https://user-images.githubusercontent.com/47655676/52858976-96957500-3151-11e9-8752-0f7cef2da094.png)

**Comment by artpar** [comment]
Hey @phanikumar252,

So ideally you wouldn't want to allow everything for guests. In case of sign-up, guests should be able to "execute" the action that's all. You want to allow the ***user_account*** entity to be acted on by guests so check "Execute" in the guests tab. 

The Read/Create here will allow guests to change the definition of the action itself which is probably something you don't want.

**Comment by phanikumar252** [comment]
hi @artpar ,

Thank you for you suggesation now i am only enabled execute for guests.
