### ISSUE TITLE
PUT method is not working when updating the data in table

### ISSUE THREAD

**Issue by phanikumar252** [daptin/daptin#52]
hi @artpar ,

I have been trying to update data in table but i am not able to process it Can you please help me on this. Thank you

curl -X PUT 'http://localhost:6336/api/item' \
-H 'Content-Type: application/json;charset=UTF-8' \
-H 'Accept: application/json, text/plain, */*' \
--data-binary '{"data":{"type":"item","attributes":{"reference_id":"8a533903-1c10-44cf-9ade-f0ca0dd050dd","name":"test","last_name":"test","amount":"20"}}}'

**Comment by artpar** [comment]
Hey @phanikumar252,

You need to use the actual entity name and not "<item>" in the url. So for example if your entity name is '<entity_name>', your PUT call will look like this:

```
curl '/api/<EntityName>/<ReferenceId>'
-X PATCH
-H 'Authorization: Bearer <Token>' --data-binary '{
                                                "data": {
                                                    "type": "<EntityName>",
                                                    "attributes": {
                                                        "confirmed": false,
                                                        "email": "update@gmail.com",
                                                        "name": "new name",
                                                        "password": "",
                                                        "permission": 127127127,
                                                    },
                                                    "id": "<ReferenceId>"
                                                }
                                              }'
```

**Comment by phanikumar252** [comment]
hi @artpar ,

Thank you the put method is working now.
