### ISSUE TITLE
Add OpenAPI Support

### ISSUE THREAD

**Issue by apimon** [daptin/daptin#54]
Good project, but needs [OpenAPI](https://swagger.io/specification/) support! We are all changing our workflows to OpenAPI, you should not ignore this industry trend. Good Luck!

**Comment by artpar** [comment]
Already have RAML spec generation. Does OpenAPI offer something much different ? I am under the impression that we can convert among the two specs using some tool

**Comment by artpar** [comment]
Added OpenAPI Spec generation of daptin APIs at /openapi.yaml
