### ISSUE TITLE
Docker Image not working

### ISSUE THREAD

**Issue by BillMeyerRSA** [daptin/daptin#55]
When running docker run -p 8080:8080 daptin/daptin 

```
> Status: Downloaded newer image for daptin/daptin:latest
> standard_init_linux.go:211: exec user process caused "no such file or directory"
```
Running on Ubuntu 18.04 Server

**Comment by artpar** [comment]
Hi,

Can you try with the travis build of the docker image once ? I will check and see what went wrong in the latest tag.

```docker run -p 9090:8080 daptin/daptin:travis```

Than open your at http://localhost:9090

**Comment by artpar** [comment]
Also can you verify the latest tag hash. I am running 8a5c4738ee5e

**Comment by BillMeyerRSA** [comment]
Yes this one worked immediately thanks
> Hi,
> 
> Can you try with the travis build of the docker image once ? I will check and see what went wrong in the latest tag.
> 
> `docker run -p 9090:8080 daptin/daptin:travis`
> 
> Than open your at http://localhost:9090
