### ISSUE TITLE
Installation and running instructions unclear

### ISSUE THREAD

**Issue by BillMeyerRSA** [daptin/daptin#56]
Downloaded the binary. Latest Release.
Run on Ubuntu 18.04. It creates the sqlite file. Long list of tables etc... 
And then... nothing. 
This is the last list of items that came up in console. 
localhost:8080 or any of the other ports, nothing. 
No clear indication what next.
Tried the docker file. Just exits with error. 
Looks like good project - will like to try it but I have no idea how to install that works. Is there maybe some dependencies that I must first load? 

```
`gopkg.in/src-d/go-git%2ev4.PlainCloneContext(0x4fdf440, 0xc000044310, 0xc0002e83f0, 0x29, 0x0, 0xc00034e700, 0x52, 0xc0002e83f0, 0x29)
	/source/vendor/gopkg.in/src-d/go-git.v4/repository.go:357 +0xcc
gopkg.in/src-d/go-git%2ev4.PlainClone(...)
	/source/vendor/gopkg.in/src-d/go-git.v4/repository.go:333
github.com/daptin/daptin/server/resource.NewMarketplaceService(0xc0002e8030, 0x24, 0xc000156240, 0x52, 0x0, 0x0, 0x1fffa1, 0xc0007521a0, 0xc0002e8360, 0x24, ...)
	/source/server/resource/market.go:130 +0x347
github.com/daptin/daptin/server/resource.(*MarketplacePackageInstallActionPerformer).refresh(0xc000196770)
	/source/server/resource/action_install_marketplace_package.go:65 +0x18c
created by github.com/daptin/daptin/server/resource.NewMarketplacePackageInstaller
	/source/server/resource/action_install_marketplace_package.go:82 +0x9b
goroutine 130 [select]:
github.com/robfig/cron.(*Cron).run(0xc000238c40)
	/source/vendor/github.com/robfig/cron/cron.go:152 +0x53e
created by github.com/robfig/cron.(*Cron).Start
	/source/vendor/github.com/robfig/cron/cron.go:127 +0x43
```

**Comment by artpar** [comment]
Hi,

Daptin should print something like this:

```
time="2019-10-05T06:27:08Z" level=info msg="Clean up config files: []"
time="2019-10-05T06:27:08Z" level=info msg="[1] Listening at port: :8080"
```

Then the dashboard and apis should be available at port 8080.

Can you include the complete logs in a file (daptin.log should be there as well next to the binary) ?

**Comment by artpar** [comment]
Hey,

Is that the full stack trace? I just came across a crash when running the binary directly and figured that the static binary was crashing because of CGOs DNS resolution behavior and found a fix here: https://github.com/concourse/concourse/issues/4141#issuecomment-514344121

Will include this in future builds. Can you confirm if this was the same issue affecting you by checking for "net.cgoIPLookup" in the crash dump. Let me know so I can close this issue..
