### ISSUE TITLE
MSSQL compatibility 

### ISSUE THREAD

**Issue by artpar** [daptin/daptin#64]
would be nice to have if not much effort to maintain

- mssql can have only one column as timestamp
- mssql cannot have limit

wip

**Comment by artpar** [comment]
- various datatype mismatches 

No ETA for this

**Comment by vinifrancosilva** [comment]
Hi! I'm a little confused. In documentation there's no mention about mssql as a database option. For what I understood this Issue covered it. 
How can I use mssql?

**Comment by artpar** [comment]
Hi @vinifrancosilva 

Set `db_type` parameter to `sqlserver` with appropriate connection string:

```bash
-db_type sqlserver -db_connection_string "sqlserver://username:password/instance?param1=value&param2=value"
```
