### ISSUE TITLE
How to tell daptin to log to a specific log location?

### ISSUE THREAD

**Issue by matthiaz** [daptin/daptin#65]
I can see `daptin.log` is hardcoded in main.go. Is there a way to overwrite this on startup?
https://github.com/daptin/daptin/blob/master/main.go#L32

- Issue seen on release and master.

**Comment by artpar** [comment]
Currently no way, I can probably read en ENV variable and set using that.

**Comment by matthiaz** [comment]
Yep, just like the other DAPTIN_ variables would be great.
Also I think there are multiple lines that need changing then e.g.: https://github.com/daptin/daptin/blob/master/server/server.go#L147

Thanks!

**Comment by artpar** [comment]
Haha, I just pushed that and missed the second one :)

**Comment by artpar** [comment]
There it is now.

**Comment by artpar** [comment]
You can checkout docker image ```daptin/daptin:travis```
