### ISSUE TITLE
-port should be a listenAddress

### ISSUE THREAD

**Issue by matthiaz** [daptin/daptin#66]
Port config and https config are a little confusing. I had to go into the source to figure out that it wasn't a port :)

https://github.com/daptin/daptin/blob/master/main.go#L56
https://github.com/daptin/daptin/blob/master/main.go#L57

You're using this in `err = http.ListenAndServe(*port, &rhs)`

But listenAndServe doesn't take a port, it takes a listenAddress. By saying :6336 you're actually saying `0.0.0.0:6336`

So if someone defines `export DAPTIN_PORT="8888"` it will fail with a weird error saying the listen address doesn't exist. It needs to be `export DAPTIN_PORT=":8888"`. Maybe we could add a check that if no ":" is found, it adds one at the front?

Matthias

**Comment by artpar** [comment]
You are right, that quick check would probably save a lot of work.

**Comment by artpar** [comment]
https://github.com/daptin/daptin/commit/63945d3601a8627feeb26c78863b7e52f14c7e2e should handle this.
