### ISSUE TITLE
Unable to access dashboard

### ISSUE THREAD

**Issue by matthiaz** [daptin/daptin#67]
The documentation at https://daptin.github.io/daptin/setting-up/settingup/

mentions: 
```
Accessing web dashboard

Open up the dashboard on http://localhost:8080/

You will be presented with the Sign-in screen. If you are on a freshly created instance, then you need to create a user first.
```

So trying to open it returns a 200 status code, but no content:
```
curl -X GET -I http://localhost:6336/ 
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type,Authorization,X-Requested-With
Access-Control-Allow-Methods: POST,GET,DELETE,PUT,OPTIONS,PATCH
Date: Thu, 23 Jan 2020 14:05:22 GMT
Content-Length: 0
```

My log shows that I'm accessing / but it's an empty response, not sure why. (notice the content length)

```
[GIN-debug] GET    /                         --> github.com/daptin/daptin/server.Main.func17 (6 handlers)
time="2020-01-23T15:04:44+01:00" level=info msg="Clean up config files: []"
time="2020-01-23T15:04:44+01:00" level=info msg="[26329] Listening at port: :6336"
time="2020-01-23T15:04:44+01:00" level=info msg="No result found for [certificate] [hostname][x1extreme]"
Failed to get admin id for user:  == sql: no rows in result set
time="2020-01-23T15:04:44+01:00" level=error msg="Failed to scan user group id from the result 1: sql: no rows in result set"
time="2020-01-23T15:04:44+01:00" level=info msg="Temp dir for certificates: /tmp"
[GIN] 2020/01/23 - 15:04:55 | 200 |      33.618µs |             ::1 | GET      /
[GIN] 2020/01/23 - 15:05:22 | 200 |      83.703µs |             ::1 | GET      /

```

Trying to access one of the endpoints does work (notice the content length)

```
➜  ~ curl -X GET -I http://localhost:6336/system
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type,Authorization,X-Requested-With
Access-Control-Allow-Methods: POST,GET,DELETE,PUT,OPTIONS,PATCH
Content-Type: application/json; charset=utf-8
Date: Thu, 23 Jan 2020 14:07:16 GMT
Content-Length: 505
```

**Comment by artpar** [comment]
Are you running the docker image ? Can you try running daptin/daptin:travis ?

daptin is unable to locate the dashboard web dir so its not serving it.

**Comment by artpar** [comment]
If you are running from source code, you need to build the included dashboard once, it is located in daptinweb/ directory. You can build with `npm run build`

**Comment by matthiaz** [comment]
Aha! Yep, I'm building from source. Trying that now. 
Also: the images on the doc sites are not shown

**Comment by artpar** [comment]
So I plan to host docs permanent at https://docs.dapt.in/ and since its the same source of both these (https://daptin.github.io/docs/) one of them has broken images.

Do note that I am yet to add documentation of a variety of features. Writing docs is hard.

**Comment by matthiaz** [comment]
Definitely is. No worries. I know this is a work in progress.

You're doing a great job.

**Comment by matthiaz** [comment]
did 
```
npm install 
npm run build
```

works :)
