### ISSUE TITLE
Accept-Language header value is `undefined` on sign up

### ISSUE THREAD

**Issue by eatonphil** [daptin/daptin#83]
When I ran this for the first time I was not able to sign up because the Accept-Language header is being set to `undefined` and the server fails on this.

I'm not sure if the UI should omit the header in this occasion or if the server should assign a default if it can't read the header or if it's this special `undefined` string.

```
level=error msg="Failed to parse Accept-Language header [undefined]: language: tag is not well-formed"
```

![image](https://user-images.githubusercontent.com/3925912/78510688-3b637f00-7765-11ea-87ac-4dc03f553dcc.png)

**Comment by artpar** [comment]
Hey

I have never seen a browser sending a 'undefined' explicitly in headers. I will Hadd login to handle this if browsers can send undefined in accept language. 

Are you adding it in your ajax call?

The accept language header anyways won't make a difference until we have enabled translations on any table.

**Comment by artpar** [comment]
Hi

Just tried out the latest docker and realized its happening in it. Have pushed a fix for this.

**Comment by artpar** [comment]
This is handled now.
