### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by roryokane** [daptin/daptin#84]
The following links quoted from the [README](https://github.com/daptin/daptin/blob/8421e7d1483c4b9d56b16b732c098677d21abc64/README.md) are broken, making it more difficult for potential users like me to evaluate the project.

> <p align="center">
>   <a href="#key-features">Features</a> •
>   <a href="#getting-started">Getting Started</a>
> </p>

The Features anchor link is broken.

> ## Why use daptin
>
> Easily consume the following features on any device
>
> - …
> - [Actions](https://daptin.github.io/daptin/actions/overview/) for abstracting out business flows

The Actions link goes to an unstyled 404 page.

> ### Users
> 
> - [Guests](https://docs.dapt.in/auth/guests)
> - [Adding users](https://docs.dapt.in/auth/users)
> - [Usergroups](https://docs.dapt.in/auth/usergroups)
> - [Data access permission](https://docs.dapt.in/auth/permissions)
> - [Social login](https://docs.dapt.in/auth/social_login)

These Users links go to an almost blank page with no error message. I think they should point to sub-sections of https://daptin.github.io/daptin/setting-up/access/.

**Comment by artpar** [comment]
Thanks, updated the links and verified the rest.

**Comment by roryokane** [comment]
The first two broken links I reported are still broken. In the [current README.md](https://github.com/daptin/daptin/blob/4ddb33882a98c2e6c0f83d7d1444c255774ff622/README.md):

- [Features][features] goes to [#key-features][features], an anchor that doesn’t exist
- [Actions][actions] goes to [https://daptin.github.io/daptin/actions/overview/][actions], a 404 page

[features]: https://github.com/daptin/daptin/blob/4ddb33882a98c2e6c0f83d7d1444c255774ff622/README.md#key-features
[actions]: https://daptin.github.io/daptin/actions/overview/

**Comment by artpar** [comment]
Updated, thanks.
