### ISSUE TITLE
Slack link on the repo

### ISSUE THREAD

**Issue by panakour** [daptin/daptin#88]
**This link is no longer active**

**Comment by artpar** [comment]
Hey @panakour you mean the Join On Slack Button ? Can you tell whats going wrong because it seems to be working for me

https://join.slack.com/t/daptin/shared_invite/enQtMzM1NTM1NTkyMDgzLWJmZmRlN2M4YzRkOTI4MDhlNWQ1YzBiMDNhMzE0NTVmNzA3NjA5ZDdkMDExZmI0M2UyMmM2NzhlNDc3M2VhZTQ

**Comment by panakour** [comment]
open the link in an incognito browser: https://join.slack.com/t/daptin/shared_invite/enQtMzM1NTM1NTkyMDgzLTVlYzBlMmM4YjMyOTk0MDc5MWJmMzFlMTliNzQwYjcxMzc5Mjk0YzEyZDIwYTljZmE5NDU3Yjk3YzQ3MzhkMzI 
![image](https://user-images.githubusercontent.com/12927166/86095835-23c53980-babb-11ea-85f5-401127bf5162.png)
