### ISSUE TITLE
Payment/membership site

### ISSUE THREAD

**Issue by bearinld004** [daptin/daptin#98]
Not an issue really an issue, was gonna ask this in the slack channel. But the invite link on the main README doesn't work.

Can daptin be molded/configured to create a system that can sell digital subscription (intake payments) and depending on the subscription unlock certain part of the site to users?

Thanks

**Comment by artpar** [comment]
Hi @bearinld004 

Yes that can be easily done in daptin.

Checkout this schema for the sample inventory schema and sale action which updates the inventory quantity

https://github.com/daptin/daptin-schema-samples/blob/master/store/schema_store_daptin.yaml

And these two actions for example integrate daptin with paypal

https://github.com/daptin/daptin-schema-samples/blob/master/pay-via-paypal/schema_pay_by_paypal_daptin.yaml

Here the `mark_as_complete_by_paypal` action endpoint can be set as the paypal server to server notification endpoint.

You can modify and mix and match them for your purpose.

**Comment by bearinld004** [comment]
Thanks  @artpar, I'm starting to see it now. 

One last thing.

https://daptin.github.io/daptin/subsite/basic_auth/

Can this authentication check be done dynamically through rules? like against a table list of paid users for example?

**Comment by artpar** [comment]
Hi @bearinld004 

You can use user groups for granting access to selective users. Create a user group, for example "paid users". Add the subsite to the group and grant execute permission and add the users to that user group. In your payment complete action you can add the user to the paid users group. 

Regards

**Comment by bearinld004** [comment]
@artpar Thanks for the detailed explanation.

I think I get the complete picture now. Will start playing around with it.
